.\" Manpage for our simple shell project
.TH OURSHELL 1 "17 04 2023"
.SH NAME
ourshell \- a simple shell for learning purposes
.SH SYNOPSIS
.B ourshell
.RI [ options ]
.SH DESCRIPTION
our simple shell is a command-line shell implemented in C for educational purposes. It supports basic command execution and has limited features compared to shells like bash.
Check our GitHub page for more information.
https://github.com/RoPallas/holbertonschool-simple_shell
.SH OPTIONS
Input "exit" to stop.

-. ls
-. pwd
-. cat
-. less
-. echo
-. man
-. head
-. tail
-. grep
.SH EXAMPLES
.IP
To start the shell, simply run:
.PP
.B ./hsh
.SH AUTHORS
Written by Rocio Pallas (6340@holbertonstudents.com) and Sebastian Maidana (6211@holbertonstudents.com)
.SH SEE ALSO
.BR sh (1),
.BR bash (1),
.BR zsh (1)
